name: assignment4

# Trigger the workflow manually using the workflow_dispatch event
on:
  workflow_dispatch:

jobs:
  build:
    # The build job runs on the latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Step to check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step to set up Docker Buildx for building multi-platform images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step to log in to Docker Hub using credentials stored in GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step to build the Docker image for the stock service
      - name: Build stock service image
        run: |
          docker build -t stock_service:latest ./stock_portfolio_app

      # Step to build the Docker image for the capital gain service
      - name: Build capital gain service image
        run: |
          docker build -t capgain_service:latest ./capital_gain_service

      # Step to tag and push the stock service image to Docker Hub
      - name: Push stock service image
        run: |
          docker tag stock_service:latest ${{ secrets.DOCKER_USERNAME }}/stock_service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/stock_service:latest

      # Step to tag and push the capital gain service image to Docker Hub
      - name: Push capital gain service image
        run: |
          docker tag capgain_service:latest ${{ secrets.DOCKER_USERNAME }}/capgain_service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/capgain_service:latest

  test:
    # The test job runs on the latest version of Ubuntu and depends on the build job
    runs-on: ubuntu-latest
    needs: build

    services:
      # Define a MongoDB service for the test job
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      # Step to check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step to set up and run Docker Compose
      - name: Set up Docker Compose
        run: |
          docker-compose up -d --build

      # Step to run tests using pytest
      - name: Run tests
        run: |
          pytest

      # Step to stop Docker Compose services
      - name: Stop Docker Compose
        run: |
          docker-compose down

  query:
    # The query job runs on the latest version of Ubuntu and depends on the test job
    runs-on: ubuntu-latest
    needs: test

    services:
      # Define a MongoDB service for the query job
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      # Step to check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step to set up and run Docker Compose
      - name: Set up Docker Compose
        run: |
          docker-compose up -d --build

      # Step to run query tests using a Python script
      - name: Run query tests
        run: |
          python query_tests.py

      # Step to stop Docker Compose services
      - name: Stop Docker Compose
        run: |
          docker-compose down